### PR TITLE
[WIP] Role: Extractor: Updated docs

### PR DESCRIPTION
**Pull request by mschultheiss83**
plaese leave comments how to integrade an update on creep.memory._move path by using  
- a custom layout for the room 
- and try not using current pathes

### CODE REVIEW

**Comment by mschultheiss83** [comment]
i ve got an bug on role_extractor.js:85 ff

i'm just on ~ 0.5 capacity of the storage, creep puts in and takes out, puts in and takes out, and so on... some ideas?

**Comment by TooAngel** [comment]
Regarding the energy put in take out:
https://github.com/TooAngel/screeps/blob/master/src/role_harvester.js#L40

I guess something similar to this will work. Calculated based on `creep.carry.energy + storage.store`.
Didn't look deeper in it, but that was usually the case.

**Comment by TooAngel** [comment]
Started an issue, so that we can discuss and form our ideas: https://github.com/TooAngel/screeps/issues/79

**Comment by mschultheiss83** [comment]
closed, see #79
and https://github.com/TooAngel/screeps/pull/111

**Pull request closed without merging**
