### PR TITLE
Move screepsplus token to config_local sample

### PR DESCRIPTION
**Pull request by Somotaw**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 32/296
    Coefficient: 0.108108108108
    Merging in 8 days 21 hours
    Age 0 days 0 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 183/296
    Coefficient: 0.618243243243
    Merging in 3 days 17 hours
    Age 0 days 1 hours

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 186/299
    Coefficient: 0.622073578595
    Merging in 3 days 13 hours
    Age 0 days 5 hours

**Comment by Nevrdid** [comment]
not sure about totally remove it from global config as for me, each things we can overwrite in local config should be in global too.
maybe just something like : 
```
screepsplusToken: '',
//read more about in local config.
```

**Comment by TooAngel** [comment]
Good point.

**Comment by Somotaw** [comment]
EIther way for me is fine :)

**Pull request merged**
