### PR TITLE
[WIP] Codeclimate

### PR DESCRIPTION
**Pull request by TooAngel**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `metric * 10 days` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:

 - @Tsungen: I just want to get this merged ASAP - @Evanito: Not sure why you are here - @mschultheiss83: I always like your reviews

**Comment by TooAngel** [comment]
DCBOT: Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by Somotaw** [comment]
👍

**Comment by Evanito** [comment]
> @Evanito: Not sure why you are here

Please remove me from the list of  'summonable' reviewers

**Comment by TooAngel** [comment]
@Evanito https://github.com/TooAngel/democratic-collaboration/pull/19 You shouldn't get summoned anymore

**Comment by Somotaw** [comment]
Would be awesome if you could list the methods your are extracting so I dont extract from same code :)

**Comment by TooAngel** [comment]
Will stop here :-) Will test these changes, if I continue I will send a new PR

**Pull request closed without merging**
