### PR TITLE
Fix mineral worker loop with result.result mineral

### PR DESCRIPTION
**Pull request by Somotaw**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: Who are you?
 - @Nevrdid: A proper review is appreciated
 - @WhiteHalmos: Who are you?

**Comment by TooAngel** [comment]
DCBOT: Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: Removing WIP label, the title is not prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 4 days -19 hours
    Age 0 days 19 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 183/296
    Coefficient: 0.618243243243
    Merging in 3 days -1 hours
    Age 0 days 19 hours

**Comment by Somotaw** [comment]
New reviews plz :)

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 183/296
    Coefficient: 0.618243243243
    Merging in 1 days 2 hours
    Age 2 days 16 hours

**Pull request merged**
