### PR TITLE
Do not care about hostile creeps if safe mode is active

### PR DESCRIPTION
**Pull request by samogot**
Do not care about hostile creeps if safe mode is active (and will not end until all hostile creeps are die)

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 0/358
    Coefficient: 0.0
    Merging in 9 days 22 hours
    Age 0 days 1 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 181/358
    Coefficient: 0.505586592179
    Merging in 4 days 21 hours
    Age 0 days 1 hours

**Comment by samogot** [comment]
@TooAngel The logic now it to keep the `underSiege` on false if there is no hostile creeps that will be alive when safemode ends. If at any time one will appear, `underSiege` will be turned on. But if for example the only Invader will die in 500 ticks - we should not spent 1000 ticks on preparation to nothing.

**Comment by TooAngel** [comment]
If the idea is mainly for invaders, we could exclude these.

The `underSiege` should instruct `nextroomers` to build ramparts and towers next to the sources, to be able to defend. If these are build they **should** build the base as if it is not `underSiege`.

Still I'm fine with the current changes.

**Comment by samogot** [comment]
> The underSiege should instruct nextroomers to build ramparts and towers next to the sources, to be able to defend. If these are build they should build the base as if it is not underSiege.

@TooAngel oh I see. But then there is another bug - this isn't work if tower can't be build due to RCL. If RCL is't enough `underSiege` is deleted, but on the next tick it is again set to true - so no base building is done

**Pull request merged**
