### PR TITLE
Change check to check for Game.cpu.tickLimit

### PR DESCRIPTION
**Pull request by Somotaw**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: Some warm words would be nice
 - @Nevrdid: A proper review is appreciated
 - @WhiteHalmos: A proper review is appreciated

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 4 days -1 hours
    Age 0 days 1 hours

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 189/302
    Coefficient: 0.62582781457
    Merging in 0 days 14 hours
    Age 3 days 3 hours

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 239/303
    Coefficient: 0.788778877888
    Merging in -1 days -7 hours
    Age 3 days 9 hours

**Pull request merged**
