### PR TITLE
Fix mySignController

### PR DESCRIPTION
**Pull request by stu43005**
This line has been printed with an incomprehensible message

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 244/505
    Coefficient: 0.483168316832
    Merging in 4 days 22 hours
    Age 0 days 5 hours

**Comment by Nevrdid** [comment]
i supose first purpose was to keep an  eye on controllers signed. So it may be better to log also when it's OK.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 245/506
    Coefficient: 0.48418972332
    Merging in 3 days 22 hours
    Age 1 days 5 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 313/513
    Coefficient: 0.610136452242
    Merging in 0 days 17 hours
    Age 3 days 4 hours

**Pull request merged**
