### PR TITLE
dont throw MemorySegmentErrors

### PR DESCRIPTION
**Pull request by mschultheiss83**
it causes too many email notifications

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 30/560
            Coefficient: 0.0535714285714
            Merging in 9 days 10 hours
            Age 0 days 0 hours

**Comment by samogot** [comment]
here
https://github.com/TooAngel/screeps/blob/master/src/prototype_creep.js#L131
something like:
```
if(!err instanceof MemorySegmentError)
   Game.notify(message, 30);
```

**Comment by mschultheiss83** [comment]
#487

**Comment by mschultheiss83** [comment]
needs rethinking / rework

**Comment by mschultheiss83** [comment]
@samogot thanks for comment

**Pull request closed without merging**
