### PR TITLE
fixed spelling mistake

### PR DESCRIPTION
**Pull request by Brutalbic**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: Some warm words would be nice
 - @Nevrdid: Who are you?
 - @Somotaw: Who are you?

**Comment by Somotaw** [comment]
is this stat spelled the same way in grafana? Maybe need fix there too then? :)

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 24/292
    Coefficient: 0.0821917808219
    Merging in 9 days -13 hours
    Age 0 days 16 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 73/292
    Coefficient: 0.25
    Merging in 7 days -12 hours
    Age 0 days 23 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 224/293
    Coefficient: 0.764505119454
    Merging in 1 days 6 hours
    Age 1 days 2 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 231/294
    Coefficient: 0.785714285714
    Merging in 1 days 0 hours
    Age 1 days 3 hours

**Pull request merged**
