### PR TITLE
feature/Visualizer-improvements

### PR DESCRIPTION
**Pull request by Somotaw**
- Added structures to visualizer (blue transparent cells, blue letters representing type(uppercase)
 - Added creeps to visualizer (yellow transparent cells, yellow letters representing type(uppercase)

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by Somotaw** [comment]
Cells or characters for structures/creeps? :)

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by Somotaw** [comment]
I think this is as ready as can be, please review :)

**Comment by Somotaw** [comment]
image

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by Somotaw** [comment]
Squashed commits

**Comment by TooAngel** [comment]
DCBOT: Removing WIP label, the title is not prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: Current status percentage: 0 votes: 0 total: 260

**Comment by TooAngel** [comment]
DCBOT: Current status percentage: 0 votes: 0 total: 260

**Comment by TooAngel** [comment]
DCBOT: Current status percentage: 0 votes: 0 total: 260

**Pull request merged**
