### PR TITLE
Creep Mineral Hotfix

### PR DESCRIPTION
**Pull request by aceofaces**
Monitor reaction product lab for target amount of minerals.
At target amount, pull minerals out of terminal.

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `metric * 10 days` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: I always like your reviews
 - @Nevrdid: A proper review is appreciated
 - @Somotaw: Not sure why you are here

**Comment by Somotaw** [comment]
WIP? or already tested?

**Comment by aceofaces** [comment]
Tested and working on private server.

**Comment by Somotaw** [comment]
what are the changes compared to previous logic? :)

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 153/288
    Coefficient: 0.53125
    Hours to merge: 16
    Age in hours: 0

**Comment by aceofaces** [comment]
Previous logic had issues when all labs were full and there were enough minerals in the terminal to fill the mineral creep.  It would continuously attempt to fill the source labs and would not execute state 8 to empty the reaction end lab0 because the mineral creep was full. Once 1000 of the target reaction is in the storage a cleanup is called and the labs cleared.

Forcing state 8 worked, but maybe forcing a cleanUpLabs would be better.

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by aceofaces** [comment]
Different cases with the mineral creep being full and blocking transfer are presenting themselves, moving to WIP for more work and testing.

**Comment by TooAngel** [comment]
DCBOT: Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: Adding WIP label, the title is prefixed with [WIP]

**Comment by Somotaw** [comment]
Roger :)

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by aceofaces** [comment]
Removing WIP, haven't had any blocking issues for a few hours of fast ticks on private.

**Comment by TooAngel** [comment]
DCBOT: Removing WIP label, the title is not prefixed with [WIP]

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 153/289
    Coefficient: 0.529411764706
    Merging in 9 days 1 hours
    Age 0 days 8 hours

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 154/290
    Coefficient: 0.531034482759
    Merging in 4 days 15 hours
    Age 0 days 0 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 180/292
    Coefficient: 0.616438356164
    Merging in 1 days 19 hours
    Age 2 days 0 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 180/292
    Coefficient: 0.616438356164
    Merging in 1 days 6 hours
    Age 2 days 13 hours

**Pull request merged**
