### PR TITLE
feature: don't build too crowded around controller.

### PR DESCRIPTION
**Pull request by XenoAmess**

### CODE REVIEW

**Review by mschultheiss83 — COMMENTED** [review]
you did this cause of https://github.com/TooAngel/screeps/pull/701
if so we don't need this

**Comment by XenoAmess** [comment]
> you did this cause of #701 if so we don't need this

mostly, but also for the grand crowd around the controller

**Review by TooAngel — COMMENTED** [review]
Not sure about this one. I did it on purpose somehow small to be able to handle also tiny rooms.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
