### PR TITLE
Fix: Invalid scoping inside a callback in costmat

### PR DESCRIPTION
**Pull request by morwoen**
The execution scope was not a room => line 50 was throwing undefined is not a function for findPropertyFiltre

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

Summoning some reviewers:
 - @TooAngel: Some warm words would be nice
 - @Nevrdid: Who are you?
 - @Somotaw: Who are you?

**Comment by morwoen** [comment]
It is not. Arrow functions always have the scope where they are defined, where normal ones have the one where they are executed, unless a different scope has been bound. Same result could be achieved with a normal function if you `return callback.bind(this)`

**Comment by TooAngel** [comment]
Finally there is someone who knows nodejs properly using the bot :-)

K, didn't know, thanks for the explanation. I guess there could be more such cases.

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 157/323
    Coefficient: 0.486068111455
    Merging in 4 days 22 hours
    Age 0 days 4 hours

**Pull request merged**
