### PR TITLE
Remove moveTo(25,25) in nextroomer execute

### PR DESCRIPTION
**Pull request by Somotaw**
Not sure why execute gets called, but this fixes them getting stuck after execute and eop message.

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: Some warm words would be nice
 - @Nevrdid: Please look at the code
 - @WhiteHalmos: I just want to get this merged ASAP

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 4 days -7 hours
    Age 0 days 7 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 183/296
    Coefficient: 0.618243243243
    Merging in 2 days 4 hours
    Age 1 days 15 hours

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 0/0
    Coefficient: 0
    Merging in 7 days -3 hours
    Age 3 days 2 hours

**Comment by TooAngel** [comment]
> As execute is an old system, i think you can totally remove the execute function for nextroomer now ;)

We have still some cases where `execute` is executed (:-)), logging it and check why can help.

**Pull request merged**
