### PR TITLE
Decrease CI server test runtime

### PR DESCRIPTION
**Pull request by TooAngel**
External Pull Requests have a runtime of ~1 hour on circleCi, so the
test runtime needs to be below this.

Moving to e.g. github actions could increase this again.

### CODE REVIEW

**Comment by mschultheiss83** [comment]
is it possible to save state as artifact and re-run it to extend tests?

**Comment by TooAngel** [comment]
> is it possible to save state as artifact and re-run it to extend tests?

puh, yeah, I think this could be somehow possible. I feel it is a bit hacky - for now I would just reduce the time so that we have at least some tests which are required.
After that we could look into better solutions.

**Review by mschultheiss83 — APPROVED** [review]
Thank you

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
