### PR TITLE
add-slash

### PR DESCRIPTION
**Pull request by Shedletsky**
fix gruntfile so that authing to screeps.com works :)

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

Summoning some reviewers:
 - @TooAngel: Some warm words would be nice
 - @Nevrdid: I just want to get this merged ASAP
 - @Somotaw: Who are you?

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 158/328
    Coefficient: 0.481707317073
    Merging in 5 days 4 hours
    Age 0 days 0 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 0/0
    Coefficient: 0
    Merging in 19 days 11 hours
    Age 5 days 12 hours

**Comment by TooAngel** [comment]
Hey, will you finish this or should I close the PR?

**Comment by Nevrdid** [comment]
https://github.com/TooAngel/screeps/commit/29b81087a9c9fb5d7d949321238ca32bf26ed7c5 ^^

**Pull request closed without merging**
