### PR TITLE
Improve private server deploy

### PR DESCRIPTION
**Pull request by TooAngel**
Add a `.localSync.js` for local folder syncronization. Excluded via `.gitignore`.

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @Nevrdid: Please look at the code
 - @WhiteHalmos: Please look at the code
 - @Somotaw: Not sure why you are here

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 4 days -23 hours
    Age 0 days 23 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 126/296
    Coefficient: 0.425675675676
    Merging in 4 days 13 hours
    Age 1 days 4 hours

**Comment by TooAngel** [comment]
> gruntfile syntax error

What is the error? I removed the output if the file is missing, but there shouldn't be an error

**Comment by Somotaw** [comment]
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Warning: Task "test" not found. Use --force to continue.

**Comment by TooAngel** [comment]
My node version is fine with it, changed to `var`

**Comment by Somotaw** [comment]
CircleCI wasnt ;)

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 3 days -12 hours
    Age 1 days 12 hours

**Comment by Somotaw** [comment]
um why no botupdate after I changed my review to approved? :o

**Pull request merged**
