### PR TITLE
Fixed codeclimate.

### PR DESCRIPTION
**Pull request by Kill4Free**
Removed unnecessary assignment.

@TooAngel is there a way to delay `worlddrive merge`?

### CODE REVIEW

**Comment by TooAngel** [comment]
This pull request will be automatically merged by [worlddriven](https://www.worlddriven.org) in 9 days and 23 hours.
Check the `worlddriven` status checks or the [dashboard](https://www.worlddriven.org/TooAngel/screeps/pull/590) for actual stats.

`Approved` reviews will speed this up.
`Request Changes` reviews will slow it down or stop it.

**Comment by TooAngel** [comment]
> @TooAngel is there a way to delay `worlddrive merge`?

When the Pull Request is opened as `Draft` it will not be merged. Besides that the time to merge depends on the reviews of the Pull Request. `Approved` reviews will speed it up, `Request Changes` will slow it down. The time for it depends on the commits on the repository. You can see more detailed stats here: https://www.worlddriven.org/TooAngel/screeps/pull/590

**Review by TooAngel — APPROVED** [review]
Still code climate complains about duplicate code, but I think it is already better.

**Comment by TooAngel** [comment]
Thank you for the review.
            This pull request will be automatically merged by [worlddriven](https://www.worlddriven.org) in 9 days, votes 2/653.

            Check the `worlddriven` status checks or the [dashboard](https://www.worlddriven.org/TooAngel/screeps/pull/590) for actual stats.

**Comment by TooAngel** [comment]
Also the time to merge depends on the last interaction with the Pull Request. So if you add a commit or force push changes the time to merge is reset, so that you are not able to sneak in nasty changes in the last minute.

Does this answer your question?

**Comment by Kill4Free** [comment]
Sorry forgot to hit the `Comment` button...

Thanks for the clarification this answers my question!

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
