### PR TITLE
[SEVERE]Fix claimer code changed by wilken which cause can never claim any room when config.nextRoom.resourceStats be false, which be default...

### PR DESCRIPTION
**Pull request by XenoAmess**
@TooAngel I cannot say there be 0 possibility that it be a bug, but I really think it possibly be a hacking-attack to this repo. 

please review as soon as possible, thanks. 

only when Memory.myRooms.length < 0 can we claim new room, yep a negative array!

### CODE REVIEW

**Review by mschultheiss83 — CHANGES_REQUESTED** [review]
you should change 
config.nextRoom.maxRooms to be like max(8 (default), Game.gcl.level/2) or something like this

**Comment by XenoAmess** [comment]
> you should change config.nextRoom.maxRooms to be like max(8 (default), Game.gcl.level / 1.5) or something like this

image

What you said is reasonable, and I would use Game.gcl.level to make it sync with existed codes in nextroomers, means `max(config.nextRoom.maxRooms, Game.gcl.level)`

**Comment by XenoAmess** [comment]
@mschultheiss83 please reply and re-review, thanks.

**Comment by mschultheiss83** [comment]
if you have 2 or more nextroomer in 2 different rooms the following line ensures that the first nextroomer wins
`  if (Memory.myRooms.length >= Game.gcl.level) {`

**Review by mschultheiss83 — CHANGES_REQUESTED** [review]
looks good to me, but we should change the config.js
```js
    maxRooms: Math.max(8, Game.gcl.level),
```

**Comment by XenoAmess** [comment]
> looks good to me, but we should change the config.js
> 
> ```js
>     maxRooms: Math.max(8, Game.gcl.level),
> ```

nope as the config will only run once, would never recalculate when you upgrade.

**Comment by XenoAmess** [comment]
> if you have 2 or more nextroomer in 2 different rooms the following line ensures that the first nextroomer wins ` if (Memory.myRooms.length >= Game.gcl.level) {`

yes, it already have such limits. so I don't think we need to add another.

**Comment by mschultheiss83** [comment]
> nope as the config will only run once, would never recalculate when you upgrade gcl level.

we could update it in `brain.prepareMemory`

**Comment by mschultheiss83** [comment]
> yes, it already have such limits. so I don't think we need to add another.
it for after respawn like me GCL 28 but like 6 rooms
so maxRooms should be near you GCL.
i have faced some memory issues when you have more than 20 rooms so i added 
`  config.nextRoom.maxRooms = Math.max(8, Game.gcl.level / 1.5); ` to the `brain.prepareMemory` function

**Comment by XenoAmess** [comment]
> > yes, it already have such limits. so I don't think we need to add another.
> > it for after respawn like me GCL 28 but like 6 rooms
> > so maxRooms should be near you GCL.
> > i have faced some memory issues when i had more than 20 rooms so i added
> > ` config.nextRoom.maxRooms = Math.max(8, Game.gcl.level / 1.5);` to the `brain.prepareMemory` function

@mschultheiss83 I understood what you wanna. please have a look at the latest version, I added a dynamic config stage,  and IMO it can do.

**Comment by XenoAmess** [comment]
@dependabot use this milestone

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
