### PR TITLE
[WIP] Move room cache to global cache

### PR DESCRIPTION
**Pull request by TooAngel**

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 173/395
    Coefficient: 0.437974683544
    Merging in 5 days 8 hours
    Age 0 days 6 hours

**Comment by democratic-collaboration** [comment]
Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
K, thx, true - Too quickly extracted some commits from my workspace branch, will close this one and redo.

**Pull request closed without merging**
