### PR TITLE
Find property filter

### PR DESCRIPTION
**Pull request by samogot**
Introduce cached find methods with property filter
Delete strange resources cache

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

**Comment by samogot** [comment]
any ideas how to fix rest of code climate issues? or just leave it as is?

**Comment by democratic-collaboration** [comment]
Adding WIP label, the title is prefixed with [WIP]

**Comment by TooAngel** [comment]
Hm, well, an interesting one. I don't have a quick good idea.

I would say the ratio `5 new issues (28 fixed)` is fine.

**Comment by democratic-collaboration** [comment]
Removing WIP label, the title is not prefixed with [WIP]

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 205/383
    Coefficient: 0.535248041775
    Merging in 8 days 13 hours
    Age 0 days 17 hours

**Comment by samogot** [comment]
@democratic-collaboration why haven't merged? :)

**Comment by TooAngel** [comment]
> @democratic-collaboration why haven't merged? :)

The time to merge is calculated as `5 + (#commits * 5)` days, this is multiplied by `#approved_reviews / #commits_on_repo`. More commits prolong the time to merge.
The Idea behind that:

**Comment by samogot** [comment]
so my rebase has increased time to merge over that was announced by @democratic-collaboration?

**Comment by TooAngel** [comment]
> so my rebase has increased time to merge over that was announced by @democratic-collaboration?

Yes, so the start time is the last interaction (push, commit, remove of WIP) with the repository.
For me it is sometimes annoying if I have to rebase my PRs a couple of times and have to wait until it gets merged (like with 'Refactor `prototype_room_init`'). From the overall and reviewer perspective, I think it makes sense. After the last changes the review should get time to review, otherwise, you can integrate some nasty stuff and nobody has time to prevent it.
If more contributors review and approve, the time to merge will decrease - Or if our weight increases due to our contribution.

**Comment by samogot** [comment]
Makes sense. In that case, wouldn't it better and clearer if @democratic-collaboration bot would announce new merging time on each interaction? also, does previous reviews counts after rebase? or should reviewer re-approve PR each time to speed it up?

**Comment by TooAngel** [comment]
> Makes sense. In that case, wouldn't it better and clearer if @democratic-collaboration bot would announce new merging time on each interaction? also, does previous reviews counts after rebase? or should reviewer re-approve PR each time to speed it up?

- I had the comments in one of the early version, it was very annoying in bigger PRs, the comments were spammed with dc messages. My current ideas are:
 - integrate it as one of the PR services like codeclimate and circleci, it seems like I can provide some more info there
 - Update the comment of dc
 - Have a frontend where you can look it up
Will work on it on the weekend, if you have improvements they are also welcome on the democratic collaboration (itself is also using dc for merging :-))

Currently the reviews before a rebase are counted in. I see your point and I guess it is better if you have to review again. I didn't implement that yet, because the review culture here is not yet very good and that would prolong the merges even more - I want to get a bit more experience first.

**Pull request merged**
