### PR TITLE
Harvester handling

### PR DESCRIPTION
**Pull request by TooAngel**
- Improve harvester setup
 - Fix harvester updateSettings
 - Spawn harvester from carry dependant on energy on drop pos

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 271/456
    Coefficient: 0.594298245614
    Merging in 3 days 10 hours
    Age 0 days 15 hours

**Comment by mschultheiss83** [comment]
would like to know how may harvesters you have seen on maximum in a room?
i changed the default amount to 2 in (getHarvesterAmount), that was enought for me

```
// if we have energy than fill our extension fast
if (this.storage && this.storage.store.energy > 2 * config.creep.energyFromStorageThreshold && this.controller.level > 5) {
   amount = 2;
}
```

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 0/0
    Coefficient: 0
    Merging in 8 days 4 hours
    Age 1 days 19 hours

**Comment by TooAngel** [comment]
> would like to know how may harvesters you have seen on maximum in a room?
> i changed the default amount to 2 in (getHarvesterAmount), that was enought for me

On room startup RCL 2/3 I have seen 6 harvesters upgrading the controller, while there is still a stack of ~1500 energy lying around.

For room > 4 for me it seems that 1 harvester is enough, I'm not yet sure for RCL 8 with 3 spawns.

**Comment by mschultheiss83** [comment]
> I'm not yet sure for RCL 8 with 3 spawns.
thats it on RCL >= 7 and if 2 * energyFromStorageThreshold than we can could use 2, for sure

**Pull request merged**
