### PR TITLE
Save username correctly

### PR DESCRIPTION
**Pull request by Somotaw**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @TooAngel: Who are you?
 - @Nevrdid: Not sure why you are here
 - @WhiteHalmos: I just want to get this merged ASAP

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 176/296
    Coefficient: 0.594594594595
    Merging in 4 days 1 hours
    Age 0 days 0 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 183/296
    Coefficient: 0.618243243243
    Merging in 3 days 9 hours
    Age 0 days 9 hours

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 232/296
    Coefficient: 0.783783783784
    Merging in 2 days -9 hours
    Age 0 days 12 hours

**Comment by Somotaw** [comment]
hmm, pretty slow merge for 232/296

**Comment by Somotaw** [comment]
or is that negative 9 hours?

**Pull request merged**
