### PR TITLE
improve harvesting resources by several creeps on low stages of game

### LINKED ISSUE #65: Nextroomers not using both sources
They bunch up and only use one source, blocking each other.

### PR DESCRIPTION
**Pull request by samogot**
- swarm mode activates by count of work body parts
- check for sources for empty adjacent spots witch fixes #65
- in swarm mode use native moveTo to handle creeps positions

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
[democratic collaboration](https://github.com/TooAngel/democratic-collaboration)
Approved reviews will speed up the merge, request changes will slow it down.

Please review the PR to help.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 205/383
    Coefficient: 0.535248041775
    Merging in 4 days 2 hours
    Age 0 days 12 hours

**Comment by samogot** [comment]
aditional review would be useful

**Comment by samogot** [comment]
looks like last commit of refactirng findNearPosition, which I ask you to re-review brokes room layout, so I reveri ir for now

**Comment by samogot** [comment]
rebased for resolving conflicts. @democratic-collaboration can be merged :)

**Pull request merged**
