### PR TITLE
Fix scout stuck on border

### PR DESCRIPTION
**Pull request by Nevrdid**
Fix scout stuck on border quickly by forcing it to move into room when scout just switch room.

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 85/407
    Coefficient: 0.208845208845
    Merging in 7 days 18 hours
    Age 0 days 3 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 283/407
    Coefficient: 0.695331695332
    Merging in 2 days 8 hours
    Age 0 days 16 hours

**Comment by TooAngel** [comment]
Well, please fix the circleci issues

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 287/411
    Coefficient: 0.698296836983
    Merging in 4 days 7 hours
    Age 0 days 4 hours

**Pull request merged**
