### PR TITLE
Test startup of code on private server

### PR DESCRIPTION
**Pull request by TooAngel**
- Start private server
 - Spawn code as bot
 - Wait
 - Check controller progress

The database is cleanup from bots and the simulation has been paused.

### CODE REVIEW

**Comment by samogot** [comment]
Maybe we can add some npm module with test server, instead of including all of this resources into repository?

**Comment by TooAngel** [comment]
Removed unnecessary files

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 291/487
    Coefficient: 0.597535934292
    Merging in 3 days 23 hours
    Age 0 days 1 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 350/487
    Coefficient: 0.718685831622
    Merging in 2 days 8 hours
    Age 0 days 11 hours

**Pull request merged**
