### PR TITLE
Check blocked rooms not so often

### PR DESCRIPTION
**Pull request by TooAngel**

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @Nevrdid: A proper review is appreciated
 - @WhiteHalmos: I just want to get this merged ASAP
 - @Somotaw: Not sure why you are here

**Comment by democratic-collaboration** [comment]
DCBOT: A new review, yeah.

    Votes: 186/306
    Coefficient: 0.607843137255
    Merging in -5 days -1 hours
    Age 8 days 22 hours

**Comment by TooAngel** [comment]
:-) k

**Comment by Somotaw** [comment]
lol?

**Comment by TooAngel** [comment]
https://github.com/TooAngel/democratic-collaboration/pull/26

**Pull request merged**
