### PR TITLE
Fix "creep.pos.findClosestEnemy is not a function"

### PR DESCRIPTION
**Pull request by DarkDestry**
Point function call to Creep.prototype.findClosestEnemy()

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 0/555
            Coefficient: 0.0
            Merging in 9 days 23 hours
            Age 0 days 0 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 30/555
            Coefficient: 0.0540540540541
            Merging in 9 days 10 hours
            Age 0 days 0 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 284/555
            Coefficient: 0.511711711712
            Merging in 4 days 20 hours
            Age 0 days 0 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 292/555
            Coefficient: 0.526126126126
            Merging in 6 days 23 hours
            Age 0 days 2 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 265/556
            Coefficient: 0.476618705036
            Merging in 7 days 13 hours
            Age 0 days 6 hours

**Comment by Evanito** [comment]
As a side note: I see that the demo collab bot is reporting the votes for the *previous* comment instead of the vote number after the current one.

**Pull request merged**
