### PR TITLE
improve Stats => Grafana #61

### PR DESCRIPTION
**Pull request by mschultheiss83**
even more public?
https://github.com/TooAngel/screeps/issues/61

### CODE REVIEW

**Comment by mschultheiss83** [comment]
@TooAngel @WhiteHalmos @Nevrdid ping for review?

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 81/461
    Coefficient: 0.175704989154
    Merging in 12 days 6 hours
    Age 0 days 2 hours

**Comment by Nevrdid** [comment]
also, name config variable screepsPlusEnable may lead to a misunderstood as it only enable agent included into basecode but it is stats.enable which totally control datas creation for screepsplus if you want to use external agent.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 306/463
    Coefficient: 0.66090712743
    Merging in 6 days 14 hours
    Age 0 days 3 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 360/465
    Coefficient: 0.774193548387
    Merging in 3 days 16 hours
    Age 0 days 20 hours

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 360/465
    Coefficient: 0.774193548387
    Merging in 2 days 10 hours
    Age 2 days 1 hours

**Pull request merged**
