### PR TITLE
Let carries dismantle structures on path

### PR DESCRIPTION
**Pull request by TooAngel**

### CODE REVIEW

**Comment by TooAngel** [comment]
DCBOT: 
This repository is under [democratic collaboration](https://github.com/TooAngel/democratic-collaboration) and will be merged automatically.

The merge decision is based on the outcome of the reviews:
 - `Approve` add the reviewer value (number of commits) to the `metric`
 - `Request changes` substract the reviewer value from the `metric`

 The merge will happen after `(1 - metric/total.votes) * (5 + pull_request.commits * 5))` calculated from the last code change.

Please review the PR to make a good democratic decision.

Summoning some reviewers:
 - @Nevrdid: I just want to get this merged ASAP
 - @WhiteHalmos: Who are you?
 - @Somotaw: I always like your reviews

**Comment by TooAngel** [comment]
DCBOT: Code update recognized, countdown starts fresh.

**Comment by Somotaw** [comment]
did you fix so they dont dismantle remote mining containers? :)

**Comment by TooAngel** [comment]
`spawn`, `storage` and `container` are excluded

**Comment by Somotaw** [comment]
where is botupdate?

**Comment by TooAngel** [comment]
Hm, don't know, try again

**Comment by TooAngel** [comment]
DCBOT: A new review, yeah.

    Votes: 174/292
    Coefficient: 0.595890410959
    Merging in 1 days -17 hours
    Age 3 days 17 hours

**Pull request merged**
