### PR TITLE
move visuals summary to dynamic location

### PR DESCRIPTION
**Pull request by sparr**
Currently the room.memory.summaryCenter has to be set manually. I plan to add a function to room.updatePosition() that keeps track of the emptiest part of the room, then moves the summary there.

### CODE REVIEW

**Comment by sparr** [comment]
I've added some rough code for placing the summary in a dynamic location. It's not ideal, but it should generally pick a better spot than the current default.

**Comment by democratic-collaboration** [comment]
A new review, yeah.

            Votes: 74/529
            Coefficient: 0.13988657845
            Merging in 16 days 6 hours
            Age 0 days 21 hours

**Comment by TooAngel** [comment]
Can you please squash the commits

**Comment by sparr** [comment]
I am attempting to squash to commits without including later pulls. Wish me luck.

**Pull request merged**
