### PR TITLE
[LOGIC REFINE]prevent sending useless reservers

### PR DESCRIPTION
**Pull request by TSStudio**
According to https://docs.screeps.com/start-areas.html
> The sector is completely separated from the outer world with a blind, indestructible wall preventing outside players from entering it. Getting inside a Novice Area is possible only by placing there your initial spawn directly.

It's impossible to travel between rooms with different status, so sending reservers is just wasting energy.  
Now check before sending them.

Updated Nov 6, 2022:

In a reserved room in a novice area, and next to normal area, walls exist but cannot be destroyed. Reservers shouldn't call structurers if the structure is not able to be destroyed.

### CODE REVIEW

**Review by mschultheiss83 — APPROVED** [review]
Nice thank you, looks good to me

**Comment by mschultheiss83** [comment]
image
same goes for scouts

**Comment by TSStudio** [comment]
> image
> same goes for scouts

Working on it, should finish in a few days. By the way, I’d like to know whether only scouts, reservers and structurers go to nearby rooms? Am I missing any other roles?

**Comment by TSStudio** [comment]
Now it should work for all roles.

**Comment by mschultheiss83** [comment]
can you rebase, please?

**Comment by TSStudio** [comment]
Yes sure, but there's some mess when I rebase, hopefully merging won't be a big problem.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
