### PR TITLE
Fix slack channel name and provide credentials for the graphs on scre…

### PR DESCRIPTION
**Pull request by TooAngel**
…epspl.us

### CODE REVIEW

**Comment by samogot** [comment]
Is it a good point to share credentials in public? This way anyone, not only Angels contributor or user can read stats, so our players would be vulnerable to other

**Comment by TooAngel** [comment]
Oh, didn't recognize that you started using it. This was a long discussion in the past, that we wanted to start sharing them internally first and provide them public later. In the sense of we have an open source code base, we can also make our graphs and maybe logs open source. - And if so, we can still win :-)

In the end it is open for discussion. If you prefer I can close this and change the password.

**Comment by TooAngel** [comment]
I often had the situation where I would love to see code from other players or get a feeling of their resources in graphs or logs. I'm pretty much wanting to go in the direction of completely open and a contributor based development.
Let's say taking me a bit out of the equation for the future development of the TooAngel account.

**Comment by samogot** [comment]
ok, that makes sence

**Pull request merged**
