### PR TITLE
fix stuck carry

### PR DESCRIPTION
**Pull request by kahojyun**
fix issue #408

### CODE REVIEW

**Comment by Nevrdid** [comment]
i did the same but with creep.isStuck() as ignore creeps

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 238/494
    Coefficient: 0.481781376518
    Merging in 5 days 0 hours
    Age 0 days 3 hours

**Comment by kahojyun** [comment]
Another bug found.  `source` is not a `RoomPosition` Object.

**Comment by Nevrdid** [comment]
well play ^^ no more sure if my harvester PR is still necessary now. exept for fullfill spawn at rcl 1.

**Comment by Nevrdid** [comment]
also, as with ignore creeps true it will disallow to have multiple harvesters mining the same time, it may be better not ignore them,

**Comment by kahojyun** [comment]
In fact, the issue hasn't been resolved completely.  We shouldn't use `moveTo` there because Sourcers will block Carriers' path.  If we update the `costMatrix` dynamically instead of setting it to its final state in the beginning, we can use `moveToMy`.

**Pull request merged**
