### PR TITLE
Rewrite visualizer using native RoomVisual

### PR DESCRIPTION
**Pull request by samogot**
- add functions for visualizing costmatrix and PathFinder search results (but not called from anywhere)

### CODE REVIEW

**Comment by democratic-collaboration** [comment]
A new review, yeah.

    Votes: 257/441
    Coefficient: 0.582766439909
    Merging in 3 days 5 hours
    Age 0 days 22 hours

**Comment by samogot** [comment]
improved

**Comment by TooAngel** [comment]
I think the visualizer shouldn't be handled via config variables. I think manual `utils` commands make more sense. Checking a room via visualizer is easier by executing `utils.showStructures(ROOMNAME)` or `Game.rooms.A1B2.showStructures()`, then by changing the config and redeploy.

**Comment by samogot** [comment]
Nah, native visualizer draws only for one tick

**Comment by TooAngel** [comment]
Ah, ok, didn't know, good to know :-)

Having commands instead of config and using memory to check if it should be drawn?

What are your experiences? I got the impression that it is annoying to use the config, especially because of the reset of the cache

**Comment by samogot** [comment]
yeah, I'm annoyed too. We can move this config to Memory, and change memory values from console)

**Pull request merged**
